name: .NET Core Desktop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build -c Release
    - name: Execute unit tests
      run: dotnet test -c Release
    - name: create nuget package
      run: dotnet pack -c Release -o pkg
    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: nuget pkg
        path: pkg
